valor1 = 5
valor2 = 3
valor3 = 2
resposta = valor1 + valor2 * valor2 	 
resposta = (valor1 + valor2) * valor2	
valor1 = 17
valor2 = 7
resposta = valor1 % valor2		
resposta = valor1 // valor2		
resposta = valor1 / valor2		
resposta = 2 ** 4		          